### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Smug246** [sfx2me/Hyperion-deobfuscator#3]
Traceback (most recent call last):
  File "c:\Users\jude\Desktop\Hyperion-deobfuscator-main\main.py", line 200, in <module>
    rreplace(f"eval(binascii{code1}.decode('8ftu'[::+-+-(-(+1))]))", code)
  File "c:\Users\jude\Desktop\Hyperion-deobfuscator-main\main.py", line 105, in rreplace
    with open('out.py', 'w') as file:file.write(filedata)
                                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jude\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u3003' in position 8648: character maps to <undefined>

**Comment by Smug246** [comment]
i was using this to get a webhook from a logger and it crashed and left the vars.py and i found it there so all good

**Comment by Smug246** [comment]
i sent u a friend request on discord because theres another file that i need deobfing

**Comment by sfx2me** [comment]
i got termed, add xKian#7978

**Comment by Smug246** [comment]
> i got termed, add xKian#7978

sent
